services:
  - type: web
    name: diabetes-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt && python app.py
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
